name: god_roll_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  firebase_core: ^2.25.4
  flutter_web_auth_2: ^3.1.1
  socket_io_client: ^2.0.0-beta.4
  firebase_messaging: ^14.7.16
  firebase_analytics: ^10.8.10
  flutter_svg: ^0.22.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  google_mobile_ads: ^5.0.0
  auto_size_text: ^3.0.0
  http: ^1.2.0
  connectivity_plus: ^6.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets: 
    - assets/icons/
    - assets/images/
