// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDooKhNWpOLWXqrnuNM54Dz6nVXUIUEMuE',
    appId: '1:116125594397:web:d4955557b6b0781a05e7f4',
    messagingSenderId: '116125594397',
    projectId: 'rollradar',
    authDomain: 'rollradar.firebaseapp.com',
    storageBucket: 'rollradar.appspot.com',
    measurementId: 'G-C5P6M7E5K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApJ_0CXuwX5Lflst-tiv0Ell1sPkVXK4o',
    appId: '1:116125594397:android:a1d751fcba7a5c9105e7f4',
    messagingSenderId: '116125594397',
    projectId: 'rollradar',
    storageBucket: 'rollradar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ftgOfTZnD1nqtShJyE0bzpfjA_qaO-U',
    appId: '1:116125594397:ios:279401836538797505e7f4',
    messagingSenderId: '116125594397',
    projectId: 'rollradar',
    storageBucket: 'rollradar.appspot.com',
    iosBundleId: 'com.example.godRollApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5ftgOfTZnD1nqtShJyE0bzpfjA_qaO-U',
    appId: '1:116125594397:ios:6a96fbfea8d9834a05e7f4',
    messagingSenderId: '116125594397',
    projectId: 'rollradar',
    storageBucket: 'rollradar.appspot.com',
    iosBundleId: 'com.example.godRollApp.RunnerTests',
  );
}
